name: Deploy to Hostinger
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Create .htaccess
        run: |
          echo '<IfModule mod_rewrite.c>' > ./dist/.htaccess
          echo 'RewriteEngine On' >> ./dist/.htaccess
          echo 'RewriteBase /' >> ./dist/.htaccess
          echo 'RewriteRule ^index\.html$ - [L]' >> ./dist/.htaccess
          echo 'RewriteCond %{REQUEST_FILENAME} !-f' >> ./dist/.htaccess
          echo 'RewriteCond %{REQUEST_FILENAME} !-d' >> ./dist/.htaccess
          echo 'RewriteCond %{REQUEST_FILENAME} !-l' >> ./dist/.htaccess
          echo 'RewriteRule . /index.html [L]' >> ./dist/.htaccess
          echo '</IfModule>' >> ./dist/.htaccess
          echo 'Options -MultiViews' >> ./dist/.htaccess
          echo '<IfModule mod_headers.c>' >> ./dist/.htaccess
          echo 'Header set Cache-Control "no-cache, no-store, must-revalidate"' >> ./dist/.htaccess
          echo 'Header set Pragma "no-cache"' >> ./dist/.htaccess
          echo 'Header set Expires 0' >> ./dist/.htaccess
          echo '</IfModule>' >> ./dist/.htaccess

      - name: Deploy to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.izicode.fr
          username: u955474908.izicode.fr
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          server-dir: /public_html/bayram/
          dangerous-clean-slate: true
